### ISSUE TITLE
Crash in Android after stopPlayer (sometime)

### ISSUE THREAD

**Issue by Vietvantue** [bambuser/react-native-bambuser-player#13]
When I stopPlayer and then play again app crash, log below:

```
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.getCurrentPosition(MediaPlayer.java)
       at com.bambuser.broadcaster.NiceMediaPlayer.getCurrentPosition + 103(NiceMediaPlayer.java:103)
       at com.bambuser.broadcaster.BroadcastPlayer.getCurrentPosition + 309(BroadcastPlayer.java:309)
       at com.bambuserplayer.BambuserPlayerView.sendOnProgressUpdate + 186(BambuserPlayerView.java:186)
       at com.bambuserplayer.BambuserPlayerView$1.run + 202(BambuserPlayerView.java:202)
       at java.util.TimerThread.mainLoop + 555(Timer.java:555)
       at java.util.TimerThread.run + 505(Timer.java:505)
```

**Comment by putuyoga** [comment]
I got this problem also 🤔

**Comment by peterlofquist** [comment]
Is this crash common? I can't seem to find any scenarios where I could trigger it. Do you have any more information available that might help us track this crash down?

**Comment by kishanbharda** [comment]
I have also same issue. App stop working after video stop. I think `onStopped()` callback not working properly.  It not firing after video stops.

**Comment by kishanbharda** [comment]
I found the solution. On android `onStopped()` is not called when video is stopped. Instead of it's called `onPlaybackComplete()` when video is stops.

**Comment by JohanSchoring** [comment]
This exception is caught since version 0.9.19 of libbambuser for Android.

**Comment by gabrielfurini** [comment]
Hey @JohanSchoring, I'm still experiencing app crashes with this kind of exceptions:
```
java.lang.IllegalStateException
  at android.media.MediaPlayer.getCurrentPosition(Native Method)
  at com.bambuser.broadcaster.NiceMediaPlayer.getCurrentPosition(NiceMediaPlayer.java:103)
  at com.bambuser.broadcaster.BroadcastPlayer.getCurrentPosition(BroadcastPlayer.java:333)
  at com.bambuserplayer.BambuserPlayerView.sendOnProgressUpdate(BambuserPlayerView.java:188)
  at com.bambuserplayer.BambuserPlayerView$1.run(BambuserPlayerView.java:204)
  at java.util.TimerThread.mainLoop(Timer.java:555)
  at java.util.TimerThread.run(Timer.java:505)
```

It happens randomly after stoping and playing some videos.

Perhaps this issue should be reopened here and revisited.

**Comment by JohanSchoring** [comment]
Ok, thanks for the clarification. According to the documentation it should be safe to invoke getCurrentPosition in the states we do, and since 0.9.19 we additionally avoid calling it in a few states when it's unnecessary, but apparently the MediaPlayer method can throw exceptions when the player is in a valid state. We will look into this. I'll leave the issue open until we have a fix for that.

**Comment by JohanSchoring** [comment]
Version 0.0.18 of react-native-bambuser-player should resolve this issue. The react-native project accidentally used multiple threads when accessing the underlying player, leading to race conditions where the player could be accessed while in an illegal state.

**Comment by gabrielfurini** [comment]
Thank you @JohanSchoring.
It seems to be working. No more crashes here 🙏
