### ISSUE TITLE
Crashing on live video,the surface has been released

### ISSUE THREAD

**Issue by santicomp2014** [bambuser/react-native-bambuser-player#15]
I'm trying to find a combination of libbambuser and react-native-bambuser-player for android, I did not find in the docs a relation between the android libbambuser and the react native version.

Currently i'm using 
"react-native": "0.59.9",
"react-native-bambuser-player": "0.0.11",
and libbambuser-0.9.14

When I try to use this library I get

```
 java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaPlayer._setVideoSurface(Native Method)
        at android.media.MediaPlayer.setSurface(MediaPlayer.java:851)
        at com.bambuser.broadcaster.NiceMediaPlayer.init(NiceMediaPlayer.java:64)
        at com.bambuser.broadcaster.BroadcastPlayer.initMediaPlayer(BroadcastPlayer.java:1190)
        at com.bambuser.broadcaster.BroadcastPlayer.access$1700(BroadcastPlayer.java:58)
        at com.bambuser.broadcaster.BroadcastPlayer$1.onResult(BroadcastPlayer.java:612)
        at com.bambuser.broadcaster.BroadcastPlayer$6.onPostExecute(BroadcastPlayer.java:752)
        at com.bambuser.broadcaster.BroadcastPlayer$6.onPostExecute(BroadcastPlayer.java:739)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
What would be a correct libbambuser/react-native-bambuser-player for RN 0.59.9 ?

I also tried on a physical device with no success, what am I missing?.

Really excited to use this library on android and ios.
Thanks for any hint

**Comment by santicomp2014** [comment]
I updated to the latest version and it worked.

The only thing I noticed is the audio distortion in Android.
Is this normal?

**Comment by santicomp2014** [comment]
Fixed, it was an audio issue with chrome and my webcam.
